#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npm run lint
npm run ts ||
(
  echo `⛔⛔🚨 Error typescript compiling 🚨⛔⛔`;
  false;
)